name: 'data_governance_poc'
version: '1.0.0'
config-version: 2

profile: 'data_governance_poc'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  data_governance_poc:
    +materialized: table
